### ISSUE TITLE
Change all HTTP requests to use guzzle/guzzle?

### ISSUE THREAD

**Issue by joonaskaskisola** [ngfw/Recipe#15]
Change all HTTP requests to guzzle/guzzle?

**Comment by Oxicode** [comment]
Mejor prueba con este https://github.com/php-curl-class/php-curl-class

**Comment by joonaskaskisola** [comment]
Why would that be a better choice?

**Comment by Oxicode** [comment]
- rápida integración
- Documentación entendible
- Api bonitas
- Soporte multicurl
