### ISSUE TITLE
Object to recipe isn`t really converting to array

### ISSUE THREAD

**Issue by 19th** [ngfw/Recipe#16]
Is it worth to have such kind of method if it's just type casting?
If Object will be recursive, it won`t really convert it to array.

```
public static function objectToArray($object)  
{
     if (is_object($object)) {
          return (array) $object;
     } else {
          throw new \Exception("Not an object");
     }
 }
```

Maybe better to replace it with known "hack" with json encode and decode or remove it at all?

**Comment by ngfw** [comment]
You are absolutely right!

**Comment by ngfw** [comment]
Thank you!
